version: '3.8'
services:
  app:
    image: your-dockerhub/demo-app:latest
    ports:
      - "8085:8085"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3307:3306"

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
