pipeline {
    agent any
    environment {
        SONAR_TOKEN = credentials('sonar-token')
        GITHUB_CRED = credentials('github-token')
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/KhairulIslamAzam/demo-dev-ops', credentialsId: 'github-token'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Static Code Analysis') {
            steps {
                sh "mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=$SONAR_TOKEN"
            }
        }
        stage('Security Scan') {
            steps {
                sh 'mvn dependency-check:check'
            }
        }
        stage('DB Migration') {
            steps {
                sh 'mvn flyway:migrate'
            }
        }
        stage('Docker Build & Push') {
            steps {
                sh 'docker build -t /home/bs-01253/Desktop/demo-app:latest .'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
